"""empty message

Revision ID: 28944bef3352
Revises: 833d79b3ec63
Create Date: 2026-08-05 10:00:55.281020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28944bef3352'
down_revision = '833d79b3ec63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('appointment_client_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('appointment_client_id_fkey'), 'client', ['client_id'], ['id'])

    # ### end Alembic commands ###
