"""permitir nulos en campos externos de cita

Revision ID: 58cc81741bf4
Revises: 607ab44ad6f7
Create Date: 2026-08-25 13:34:33.740870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58cc81741bf4'
down_revision = '607ab44ad6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('calendly_event_uri',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('calendly_invitee_uri',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('google_calendar_event_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('cancel_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('cancel_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('google_calendar_event_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('calendly_invitee_uri',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('calendly_event_uri',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
