"""empty message

Revision ID: 9998a7a938fb
Revises: 58cc81741bf4
Create Date: 2026-08-25 17:08:20.559099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9998a7a938fb'
down_revision = '58cc81741bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('biografi',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('biografi',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
