"""empty message

Revision ID: b71b7d0fff92
Revises: 70b931ed3070
Create Date: 2026-09-04 10:45:47.983999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71b7d0fff92'
down_revision = '70b931ed3070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendly_event_uri', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('calendly_invitee_uri', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cancel_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('cancel_url')
        batch_op.drop_column('google_calendar_event_id')
        batch_op.drop_column('calendly_invitee_uri')
        batch_op.drop_column('calendly_event_uri')

    # ### end Alembic commands ###
